apiVersion: "v1"
kind: Pod
metadata:
  name: solitaire
  labels:
    app: solitaire
spec:
  containers:
    - name: solitaire
      image: tany2020/pipeline:tagVersion
      ports:	
        - containerPort: 8080
